### ISSUE TITLE
Error when doing pip install

### ISSUE THREAD

**Issue by davidbullado** [davidhi7/ddcci-plasmoid#11]
Hi, there is this error when I run the command "pip install ddcci-plasmoid-backend" :
```
ERROR: Could not find a version that satisfies the requirement ddcci-plasmoid-backend (from versions: none)
ERROR: No matching distribution found for ddcci-plasmoid-backend
```

pip3 --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

**Comment by davidhi7** [comment]
As of version 0.1.5 only python 3.8 or later is required, so installing it should now work.
