### ISSUE TITLE
python backend with conda

### ISSUE THREAD

**Issue by d-vogel** [davidhi7/ddcci-plasmoid#12]
Thanks David for taking the time to do what I had planned for a long time.

I solved the issue myself, but posting it for others.

# The symptoms:
When installing the plamoid (and the python backend) on my system (openSuse TW) with conda, the plasmoid was not able to find the python module (the error in the plasmoid is "Unable to parse error message").

# The problem:
This is because with conda installed, the python used by default is the python from your "base" environment. However in my case, because the base environment was python3.7 and ddcci_plasmoid_backend requires 3.10, pip installed it in the system python (in `/usr/lib/python3.10/`).

# The solution
Update the conda "base" environement to 3.10 (`conda update -n base python`) and this time pip installs in the right location.

# Discussion
This is not a super elegant solution anyways, as it doesn't make much sense to install the backend for a plasmoid in a user-specific conda env, so I'm kind of opening the discussion here: 
how can we get the plasmoid to run using the system python (ie `/usr/bin/python`) so that we can just `conda deactivate && pip install ddcci_plasmoid_backend` or even better, have a rpm package containing the whole plasmoid ?

**Comment by davidhi7** [comment]
> how can we get the plasmoid to run using the system python (ie /usr/bin/python) so that we can just conda deactivate && pip install ddcci_plasmoid_backend 

Having no knowledge about how conda works and what it does I can't comment on that. As discussed in another issue, the 3.10 requirement is kind of arbitrary and I will try to lower it with some testing to make this widget compatible with more configurations. However, I have no idea how to deal with conda-specific issues.

> have a rpm package containing the whole plasmoid 

Native distro packages are really the best solution for packaging. I don't plan on providing such packages for distros except for archlinux, though I will gladly support others doing this.

**Comment by CatEricka** [comment]
Maybe you need #7, so any kind of backend can be used via a custom scripts.

**Comment by davidhi7** [comment]
I looked into the required python version, now the backend supports python 3.8 with little changes but 3.7 would require more changes which I don't plan to implement for an almost five year old release. Also, the option to set a custom backend command is now merged, so one could run some conda-specific commands beforehand.
