### ISSUE TITLE
Feature request: make this great widget System Tray aware?

### ISSUE THREAD

**Issue by rburcham** [davidhi7/ddcci-plasmoid#13]
Title says it all.  I have many monitors on my workstation and this widget has great practical value for me.  My only complaint is an aesthetic one:  it looks awkward on the panel when next to the system tray.

<img width="501" alt="ddcci-plasmoid-systemtray-Screenshot_20230414_093808" src="https://user-images.githubusercontent.com/11066282/232075616-baec48ae-aac4-411c-b84f-f4821b6cf474.png">

I don't know what it entails, but would it be possible to make ddcci-plasmoid a system tray component, so that its display enablement/disablement would be available in the system tray config panel, and its panel icon would be grouped with the rest of the system tray items?

<img width="515" alt="system-tray-config-Screenshot_20230414_094345" src="https://user-images.githubusercontent.com/11066282/232076583-d7e260a1-91f8-4e62-8829-66e75a09b3fe.png">

Please consider a low priority feature request, but a prized one.

**Comment by davidhi7** [comment]
Already implemented, only needs to be merged into main. I'll release a new version featuring it this weekand.

**Comment by davidhi7** [comment]
I just released version 0.1.5 which implements this.
