### ISSUE TITLE
Monitor requirements

### ISSUE THREAD

**Issue by SylEleuth** [davidhi7/ddcci-plasmoid#14]
What monitors should have to make the plasmoid work with them? I have 2 monitors (and 1 projector). They have DCC/CI option enabled, yet `ddcutil detect` describe them all as "Invalid display"
```
Invalid display
   I2C bus:  /dev/i2c-3
   DRM connector:           card0-DP-1
   EDID synopsis:
      Mfg id:               BNQ - UNK
      Model:                BenQ GW2760HS
      Product code:         30922  (0x78ca)
      Serial number:        F4E01278SL0
      Binary serial number: 21573 (0x00005445)
      Manufacture year:     2014,  Week: 16
   DDC communication failed

Invalid display
   I2C bus:  /dev/i2c-6
   DRM connector:           card0-HDMI-A-1
   EDID synopsis:
      Mfg id:               NLK - UNK
      Model:                MStar Demo
      Product code:         48  (0x0030)
      Serial number:        
      Binary serial number: 1 (0x00000001)
      Manufacture year:     2014,  Week: 10
   DDC communication failed

Invalid display
   I2C bus:  /dev/i2c-7
   DRM connector:           card0-DVI-D-1
   EDID synopsis:
      Mfg id:               DEL - Dell Inc.
      Model:                DELL E2211H
      Product code:         41074  (0xa072)
      Serial number:        NJ91T24I22KB
      Binary serial number: 842156866 (0x32324b42)
      Manufacture year:     2012,  Week: 16
   DDC communication failed
```
What am I missing?

**Comment by CatEricka** [comment]
What is your version of `ddcutil`?  Updating to the latest version may help fix this issue. This plasmoid relies on ddcutil to work, and if it can't handle communicating with the display, unfortunately plasmoid doesn't have a way to deal it either.

**Comment by CatEricka** [comment]
On the other hand, as far as I know, whether ddc/ci can work also depends on many conditions: graphics card, motherboard, docking station, drivers, and even the display cable, etc.

**Comment by SylEleuth** [comment]
> What is your version of `ddcutil`?

My version is 1.3.0. I'm on Arch and it looks like a newest version is still tested in official repo. I've installed one from AUR (v1.4) and nothing changed.
Every display is connected with a different cable - dvi, hdmi and dp. And unfortunately I don't have access to other computers.
I will look for a solution on ddcutil issue tracker.
