### ISSUE TITLE
Feature Request - support integrating into system tray

### ISSUE THREAD

**Issue by peterhoeg** [davidhi7/ddcci-plasmoid#2]
You're a real life-saver - this is great!!

What I would like if possible is to have the applet show in the system tray rather than having to take up a whole "row" on my panel (see attached).

![Screenshot_20230410_100455](https://user-images.githubusercontent.com/722550/230881181-258c0677-6559-42b0-b094-e7c51b709a55.png)

I'm not sure if all that's needed is a `metadata.desktop` file with `X-Plasma-NotificationArea=true`.

**Comment by davidhi7** [comment]
This attribute does in fact integrate the widget into the system tray, which is something I planned to implement but had no idea how. Though some further work is required to fix layout issues and a duplicate title.
![ddcci-plasmoid-#2](https://user-images.githubusercontent.com/77309510/230970282-3b67420e-fc82-408e-86e9-3ce35ecec3b5.png)

**Comment by davidhi7** [comment]
I just released version 0.1.5 which implements this. Thank you for pointing me into the right direction with `X-Plasma-NotificationArea=true`!
