### ISSUE TITLE
ddcci_plasmoid_backend unavailable

### ISSUE THREAD

**Issue by RokeJulianLockhart** [davidhi7/ddcci-plasmoid#31]
This happened a few updates ago. cpe:/o:opensuse:tumbleweed:20230624

![image](https://github.com/davidhi7/ddcci-plasmoid/assets/42837531/1b9a8759-053d-4a14-aa3a-07119cbcc68a) ![image](https://github.com/davidhi7/ddcci-plasmoid/assets/42837531/5b8bf76e-a313-4f98-af82-dfe395eb7800)

**Comment by davidhi7** [comment]
The error wont hide itself (yet), but it shouldn't appear again after closing it.

**Comment by RokeJulianLockhart** [comment]
```log
RokeJulianLockhart@s1e8h4:~> pip3 install --user ddcci-plasmoid-backend
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try
    zypper install python311-xyz, where xyz is the package
    you are trying to install.
    
    If you wish to install a non-rpm packaged Python package,
    create a virtual environment using python3.11 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-rpm packaged Python application,
    it may be easiest to use `pipx install xyz`, which will manage a
    virtual environment for you. Install pipx via `zypper install python311-pipx` .

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Comment by davidhi7** [comment]
See #33 and https://github.com/davidhi7/ddcci-plasmoid#installing-the-backend-with-pip-fails-printing-this-environment-is-externally-managed.

**Comment by RokeJulianLockhart** [comment]
@davidhi7, do you know which version of Python to use? I don't know which your plasmoid uses.

```log
RokeJulianLockhart@s1e8h4:~> cnf pipx

The program 'pipx' can be found in following packages:
  * python310-pipx [ path: /usr/bin/pipx, repository: download.opensuse.org-oss ]
  * python311-pipx [ path: /usr/bin/pipx, repository: download.opensuse.org-oss ]
  * python39-pipx [ path: /usr/bin/pipx, repository: download.opensuse.org-oss ]
  * python310-pipx [ path: /usr/bin/pipx, repository: openSUSE-20230920-0 ]
  * python311-pipx [ path: /usr/bin/pipx, repository: openSUSE-20230920-0 ]
  * python39-pipx [ path: /usr/bin/pipx, repository: openSUSE-20230920-0 ]

Try installing with:
    sudo zypper install <selected_package>

RokeJulianLockhart@s1e8h4:~> sudo zypper install pipx
[sudo] password for root: 
Loading repository data...
Reading installed packages...
'pipx' not found in package names. Trying capabilities.
No provider of 'pipx' found.
Resolving package dependencies...
Nothing to do.
```

It doesn't want to choose for me.

**Comment by davidhi7** [comment]
Installing pipx for the system python version, so the version reported by "python -V", should be the best option. So `python311-pipx` if the python version is 3.11.x for example.

**Comment by RokeJulianLockhart** [comment]
```log
RokeJulianLockhart@s1e8h4:~> python -V

The program 'python' can be found in following packages:
  * python-base [ path: /usr/bin/python, repository: download.opensuse.org-oss ]
  * python-base [ path: /usr/bin/python, repository: https-download.opensuse.org-1ff5d8a2 ]
  * python-base [ path: /usr/bin/python, repository: openSUSE-20230920-0 ]

Try installing with:
    sudo zypper install <selected_package>

RokeJulianLockhart@s1e8h4:~> python3 -V
Python 3.11.5
```

You mean `python3`, right? We'd be dealing with Python 2 otherwise.

**Comment by RokeJulianLockhart** [comment]
```log
RokeJulianLockhart@s1e8h4:~> sudo zypper install python311-pipx
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 3 NEW packages are going to be installed:
  python311-argcomplete python311-pipx python311-userpath

3 new packages to install.
Overall download size: 265.7 KiB. Already cached: 0 B. After the operation, additional 716.9 KiB will be used.
Continue? [y/n/v/...? shows all options] (y): y   
Retrieving: python311-argcomplete-3.1.1-1.2.noarch (Main Repository (OSS))                                                                                                                                                                                                                              (1/3),  79.0 KiB    
Retrieving: python311-argcomplete-3.1.1-1.2.noarch.rpm ..................................................................................................................................................................................................................................................[done (43.9 KiB/s)]
Retrieving: python311-userpath-1.9.0-1.1.noarch (Main Repository (OSS))                                                                                                                                                                                                                                 (2/3),  32.5 KiB    
Retrieving: python311-userpath-1.9.0-1.1.noarch.rpm ......................................................................................................................................................................................................................................................[done (1.2 KiB/s)]
Retrieving: python311-pipx-1.2.0-2.2.noarch (Main Repository (OSS))                                                                                                                                                                                                                                     (3/3), 154.2 KiB    
Retrieving: python311-pipx-1.2.0-2.2.noarch.rpm ........................................................................................................................................................................................................................................................[done (468.1 KiB/s)]

Checking for file conflicts: .........................................................................................................................................................................................................................................................................................[done]
(1/3) Installing: python311-argcomplete-3.1.1-1.2.noarch .............................................................................................................................................................................................................................................................[done]
(2/3) Installing: python311-userpath-1.9.0-1.1.noarch ................................................................................................................................................................................................................................................................[done]
(3/3) Installing: python311-pipx-1.2.0-2.2.noarch ....................................................................................................................................................................................................................................................................[done]
RokeJulianLockhart@s1e8h4:~> pipx install ddcci-plasmoid-backend
  installed package ddcci-plasmoid-backend 0.1.8, installed using Python 3.11.5
  These apps are now globally available
    - ddcci_plasmoid_backend
done! ✨ 🌟 ✨RokeJulianLockhart@s1e8h4:~>
```

![Screenshot_20231001_203251](https://github.com/davidhi7/ddcci-plasmoid/assets/42837531/43c7ed1b-36d0-467d-96ea-c8faff7cda43)

**Comment by davidhi7** [comment]
The `backend executable command` in the settings must be set to `~/.local/bin/ddcci_plasmoid_backend`.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/davidhi7/ddcci-plasmoid/issues/31#issuecomment-1742212161

@davidhi7, that made it worse, unfortunately.

![Screenshot_20231002_170007](https://github.com/davidhi7/ddcci-plasmoid/assets/42837531/74b9b9de-5be4-4b28-9e25-24f624c7232a)

**Comment by CatEricka** [comment]
Have you installed `ddcutil`? 

Please use command `~/.local/bin/ddcci_plasmoid_backend` in a terminal to get full log.

**Comment by RokeJulianLockhart** [comment]
0.	```log
	RokeJulianLockhart@s1e8h4:~> sudo zypper install ddcutil
	[sudo] password for root: 
	Loading repository data...
	Reading installed packages...
	Resolving package dependencies...

	The following recommended package was automatically selected:
	ddcutil-i2c-udev-rules

	The following 3 NEW packages are going to be installed:
	ddcutil ddcutil-i2c-udev-rules libddcutil4

	3 new packages to install.
	Overall download size: 662.9 KiB. Already cached: 0 B. After the operation, additional 1.7 MiB will be used.
	Continue? [y/n/v/...? shows all options] (y): y
	Retrieving: libddcutil4-1.4.1-2.3.x86_64 (Main Repository (OSS))                                                                                                                                                                                                                                        (1/3), 258.3 KiB    
	Retrieving: libddcutil4-1.4.1-2.3.x86_64.rpm .............................................................................................................................................................................................................................................................[done (1.1 MiB/s)]
	Retrieving: ddcutil-i2c-udev-rules-1.4.1-2.3.noarch (Main Repository (OSS))                                                                                                                                                                                                                             (2/3),  15.8 KiB    
	Retrieving: ddcutil-i2c-udev-rules-1.4.1-2.3.noarch.rpm ..................................................................................................................................................................................................................................................[done (1.1 KiB/s)]
	Retrieving: ddcutil-1.4.1-2.3.x86_64 (Main Repository (OSS))                                                                                                                                                                                                                                            (3/3), 388.9 KiB    
	Retrieving: ddcutil-1.4.1-2.3.x86_64.rpm ...............................................................................................................................................................................................................................................................[done (891.4 KiB/s)]

	Checking for file conflicts: .........................................................................................................................................................................................................................................................................................[done]
	(1/3) Installing: libddcutil4-1.4.1-2.3.x86_64 .......................................................................................................................................................................................................................................................................[done]
	(2/3) Installing: ddcutil-i2c-udev-rules-1.4.1-2.3.noarch ............................................................................................................................................................................................................................................................[done]
	(3/3) Installing: ddcutil-1.4.1-2.3.x86_64 ...........................................................................................................................................................................................................................................................................[done]
	RokeJulianLockhart@s1e8h4:~>
	```

0.	![image](https://github.com/davidhi7/ddcci-plasmoid/assets/42837531/2412237a-1a80-400b-8bd8-48d83a5901da)

0.	```sh
	sudo modprobe i2c-dev
	```

0.	![image](https://github.com/davidhi7/ddcci-plasmoid/assets/42837531/21eb62d6-f505-468a-a4e7-1200c8386b36)
