### ISSUE TITLE
Brightness reverts to on-screen monitor GUI config during shutdown.

### ISSUE THREAD

**Issue by rokejulianlockhart** [davidhi7/ddcci-plasmoid#36]
Per https://github.com/JonMagon/plasma-screendimmer/issues/2#issuecomment-1636040125, reported here.

**Comment by davidhi7** [comment]
So just to reiterate, the brightness set by the widget is reset after every reboot.
Can you send the output of `python -m ddcci_plasmoid_backend --debug detect`? (skip the `python -m` part if you're using pipx).

Do you use any application that also does DDC/CI communication, for example vdu_controls? I think the most likely cause is that some other application overwrites the brightness every time you boot/shutdown.

To verify it is unrelated to other applications, try to boot into a Linux installer image, install ddcutil, run `ddcutil detect`, then run `ddcutil setvcp --display <ID of the monitor> 10 <brightness value>`. Reboot directly into a Linux installer image again and pay attention if the brightness is overwritten in the process.

**Comment by davidhi7** [comment]
Similar to #37, this might be related to powerdevil, try to disable all display brightness related options in the KDE system settings under Power management > Energy saving.
