### ISSUE TITLE
Screen Brightness dimming automatically upon playing Youtube Videos

### ISSUE THREAD

**Issue by RemovedMoney326** [davidhi7/ddcci-plasmoid#37]
So, I've noticed my screen dimming noticeably below the intended setting whenever I play a Youtube Video. After closing the video, I need to click within the widgets brightness slider again on the same spot it was originally left on in order for the monitor to brighten up again.

I use an Nvidia GPU btw, and otherwise the widget works great.

**Comment by davidhi7** [comment]
Some versions of powerdevil (KDEs power management software) are compiled with ddcutil support and thus can interfere with this widget.
Try to disable all display brightness related options in the KDE system settings under Power management > Energy saving. You could also look into this post.
