### ISSUE TITLE
Ubuntu 22.04 - i2c included in Kernel instead of module

### ISSUE THREAD

**Issue by BushwaTheGoat** [davidhi7/ddcci-plasmoid#46]
The command on the readme doesn't show i2c-dev to be loaded if it's compiled into the kernel.
lsmod doesn't return anything, despite i2c-dev being ready to use:
```
$ lsmod | grep i2c_dev
$ grep I2C_CHARDEV /boot/config-$(uname -r)
CONFIG_I2C_CHARDEV=y
$
```
It took me a while to understand that I was looking for another error.
Please include a note on the readme.
More about this on [a question on askubuntu.com](https://askubuntu.com/questions/1467943/how-to-load-and-install-the-i2c-dev-kernel-module-on-22-04).

**Comment by davidhi7** [comment]
I addressed this in the readme, now explicitly loading the i2c_dev module is only guided if it is required.
