### ISSUE TITLE
Feature Request: changeable widget width when in panel

### ISSUE THREAD

**Issue by Peter-Ries** [davidhi7/ddcci-plasmoid#48]
I use your great plasmoid in panel left to system tray. I also have Command Output widget running. The ddcci-plasmoid consumes more width in the panel which makes it look a little odd (I'm a little picky with this ;) ). While I can adjust Command Output plasmoid width in the config ddcci comes with no option / a fixed width. I couldn't even fugure out where to play around in qml code.

Would be great if this can be adjusted or if you can give me a hint where to reduce width to e. g. 80%.

Thanks.

![image](https://github.com/davidhi7/ddcci-plasmoid/assets/48622005/a0b1c176-8ddb-4098-b08a-b7028fb32041)

**Comment by davidhi7** [comment]
Did you pin the widget to the sys tray instead of adding it to the panel manually? See https://github.com/davidhi7/ddcci-plasmoid#integrate-into-systemtray

**Comment by Peter-Ries** [comment]
Oh, I shoud read better. I always mix up system-tray and the panel. I could find your plasmoid in the "real" systray as deactivated - made it visible and removed the manually dragged and dropped plasmoid. Now everything looks pretty!!!

Thanks a lot :)

![image](https://github.com/davidhi7/ddcci-plasmoid/assets/48622005/2854ca8d-b0e1-4539-a67a-5639cfd1f40a)
