### ISSUE TITLE
Widget not showing any monitors but an error

### ISSUE THREAD

**Issue by ivaylo-iliev** [davidhi7/ddcci-plasmoid#5]
I am having some strange issue with this widget. Installed it following the instructions on the repo but getting "Unable to parse error response" error on the widget itself. When trying to run "ddcutil detect" I get output as follows:

```
Invalid display
I2C bus: /dev/i2c-5
DRM connector: card0-eDP-1
EDID synopsis:
Mfg id: LEN - Lenovo Group Limited
Model:
Product code: 16570 (0x40ba)
Serial number:
Binary serial number: 0 (0x00000000)
Manufacture year: 2018, Week: 0
DDC communication failed
This is an eDP laptop display. Laptop displays do not support DDC/CI.
Display 1
I2C bus: /dev/i2c-6
DRM connector: card0-DP-1
EDID synopsis:
Mfg id: GSM - Goldstar Company Ltd (LG)
Model: LG HDR 4K
Product code: 30471 (0x7707)
Serial number:
Binary serial number: 538649 (0x00083819)
Manufacture year: 2020, Week: 7
VCP version: 2.1
```

I am also able to change settings of the monitor using ddcutil and dddcontrol. I got the same error both under Manjaro and Kubuntu

**Comment by ivaylo-iliev** [comment]
I just saw this might be a duplicate of Issue #3 Possible solution would be for the widget to ignore "invalid" displays.

**Comment by davidhi7** [comment]
'invalid' displays should be handled properly and thus unrelated to the issue.

I just released v0.1.3 which prints a lot more debug output. Could you update the backend (`pip install -U ddcci_plasmoid_backend` and provide the output of `python -m ddcci_plasmoid_backend --debug detect`?

**Comment by ivaylo-iliev** [comment]
I will not be able to provide the output for the next few days since I am traveling and cannot connect to the secondary display. I will provide it  when possible.

**Comment by davidhi7** [comment]
No hurry, but once you're back please try to install the latest version v1.4.1 of ddcutil. A similar bug was fixed by this.

**Comment by ivaylo-iliev** [comment]
The ddcutil upgrade fixed the issue.
