### ISSUE TITLE
Monitors detected, but sliding the brightness slider does nothing

### ISSUE THREAD

**Issue by leledumbo** [davidhi7/ddcci-plasmoid#50]
```
$ ddcutil detect
Display 1
   I2C bus:  /dev/i2c-12
   DRM connector:           card1-DP-1
   EDID synopsis:
      Mfg id:               HKC - UNK
      Model:                27E3Q
      Product code:         10038  (0x2736)
      Serial number:        0000000000001
      Binary serial number: 1 (0x00000001)
      Manufacture year:     2023,  Week: 9
   VCP version:         2.1
```
Looking at the code, it seems to execute:
```
$ ddcutil setvcp --bus 12 10 <brightness value>
```
indeed the command doesn't work on my external monitor. The one that works is this:
```
$ xrandr --output DP-1 --brightness 0.2
```
I don't know what's wrong with the ddcutil command.

**Comment by davidhi7** [comment]
What error messages does the setvcp command print? Try to run this command with either `--noverify` or `--sleep-multiplier 2` appended.

The fact that xrandr doesn't fail is not surprising. xrandr does only change the brightness on the software level, effectively making all colours darker before they are sent to the screen. ddcutil changes the brightness on the hardware level by telling the monitor to adjust the physical backlight brightness. This causes ddcutil to be sensitive to monitors with poor DDC/CI implementation, which might be the case here.

**Comment by leledumbo** [comment]
> What error messages does the setvcp command print?

Nothing, the command executes successfully with return value of 0.
It could very well be a bad firmware, the downside of a well specced cheap monitor.

**Comment by davidhi7** [comment]
If the ddcutil arguments I mentioned don't help either, there is nothing I can do about it.  You could open an issue in the ddcutil repository to try to get further help: https://github.com/rockowitz/ddcutil.

**Comment by leledumbo** [comment]
Since the issue doesn't seem to be related to your app, I'm closing this and continue it in ddcutil issue instead. Thank you.
