### ISSUE TITLE
ddcci-plasmoid make ddcutil throw error every minute.

### ISSUE THREAD

**Issue by Bryan2333** [davidhi7/ddcci-plasmoid#51]
I'm using ddcci-plasmod 0.2. And my ddcutil version is 2.0.0.

It seems that ddcci-plasmoid run ddcutil every minute, which make ddcutil throw an error.

![Screenshot_20231120_204418.webp](https://s2.loli.net/2023/11/20/WzmThjrRaFbExn6.webp)

**Comment by davidhi7** [comment]
Ddcutil is called every minute so the widget responses to connected/disconnected monitors.

Regarding the ddcutil error messages, there is nothing I can do about them. They indicate that some error occurred in ddcutil, you may file an issue in the ddcutil bug tracker if everything works otherwise.
