### ISSUE TITLE
Error while finding module specification

### ISSUE THREAD

**Issue by VassilisAlexiou** [davidhi7/ddcci-plasmoid#54]
I followed your installation guide very carefully but I get this error
![Screenshot_20231202_133335](https://github.com/davidhi7/ddcci-plasmoid/assets/25265072/c83f089c-ee24-4872-9825-153df2978147)
Any ideas about what the problem might be?
Thanks ....

**Comment by davidhi7** [comment]
I assume you installed the package using `pipx`, considering you changed the backend executable command to `/home/vassilis/.local/bin/ddcci_plasmoid_backend`. If so, please post the output of `pipx environment` and `ls -l/home/vassilis/.local/bin/`.

**Comment by rghedin** [comment]
Same issue here, @davidhi7, so I'm posting the requested outputs to try to fix this issue.

From `pipx environment`:

```
PIPX_HOME=/home/rodrigo/.local/pipx
PIPX_BIN_DIR=/home/rodrigo/.local/bin
PIPX_SHARED_LIBS=/home/rodrigo/.local/pipx/shared
PIPX_LOCAL_VENVS=/home/rodrigo/.local/pipx/venvs
PIPX_LOG_DIR=/home/rodrigo/.local/pipx/logs
PIPX_TRASH_DIR=/home/rodrigo/.local/pipx/.trash
PIPX_VENV_CACHEDIR=/home/rodrigo/.local/pipx/.cache

Only PIPX_HOME and PIPX_BIN_DIR can be set by users in the above list.
```

And for `ls -l /home/<user>/.local/bin`:

```
total 4
lrwxrwxrwx 1 rodrigo rodrigo 81 jan 24 19:06 ddcci_plasmoid_backend -> /home/rodrigo/.local/pipx/venvs/ddcci-plasmoid-backend/bin/ddcci_plasmoid_backend
```

**Comment by davidhi7** [comment]
Does the issue appear when executing `~/.local/bin/ddcci_plasmoid_backend` manually? Note that this path must not be treated as a python file, passing this as an argument to `python` wont work.

**Comment by rghedin** [comment]
I'm not sure if I followed (sorry, not very knowledgeable in CLI), but I've tried this:

```
rodrigo@debian:~$ python3 ~/.local/bin/ddcci_plasmoid_backend -d
Traceback (most recent call last):
  File "/home/rodrigo/.local/bin/ddcci_plasmoid_backend", line 5, in <module>
    from ddcci_plasmoid_backend.__main__ import main
ModuleNotFoundError: No module named 'ddcci_plasmoid_backend'
```

It seems the same error shows up.

**Comment by davidhi7** [comment]
You need to execute `~/.local/bin/ddcci_plasmoid_backend` without putting anything before it.

**Comment by rghedin** [comment]
There it is:

```
rodrigo@debian:~$ ~/.local/bin/ddcci_plasmoid_backend
usage: plasma-ddcci-backend [-h] [-d] [--debug-log LOG_FILE]
                            {version,detect,set-brightness} ...
plasma-ddcci-backend: error: the following arguments are required: command
```

**Comment by davidhi7** [comment]
I may have misunderstood your last response. This command works as intended, at this point you only need to set it as "Backend executable command" in the widget configuration.
The error is printed because no argument is passed. The widget code will declare all required arguments itself, for testing you can run `~/.local/bin/ddcci_plasmoid_backend detect`.

**Comment by rghedin** [comment]
Sorry, I'm new on Linux. It worked! Thank you :)
