### ISSUE TITLE
Support Plasma 6

### ISSUE THREAD

**Issue by PegasisForever** [davidhi7/ddcci-plasmoid#58]
![image](https://github.com/davidhi7/ddcci-plasmoid/assets/39028532/0c053a56-684f-41ff-87ac-d7cc5d42b10d)

Currently the widget doesn't work on Plasma 6.0 beta 1.

https://develop.kde.org/docs/plasma/widget/porting_kf6/

**Comment by davidhi7** [comment]
I just merged Plasma 6 support into main and published the Plasma 6 widget to store.kde.org, see https://store.kde.org/p/2114471.
