### ISSUE TITLE
Including this plasmoid cause Plasma to stop rendering the Task Bar.

### ISSUE THREAD

**Issue by Azercoco** [davidhi7/ddcci-plasmoid#62]
How to reproduce :

- Install DDCCI Plasmoid
- Add it to the taskbar
-  Kill and relaunch Plasma 
- Taskbar is no longer visible
- If the plasma config is change to what it was before adding it, the taskbar is visible again.

System information : 

Linux version 6.6.9-arch1-1
plasmashell 5.27.10

**Comment by davidhi7** [comment]
I'm unable to reproduce this myself. Please post the relevant output of `journalctl` when reproducing this (e.g. run `sudo journalctl -f` before killing and relaunching plasmashell).

**Comment by Azercoco** [comment]
Here is my log :

`hecking screens: available: (QScreen(0x5631eb96c160, name="HDMI-0"), QScreen(0x5631eb96c250, name="DP-5")) redundant: QHash() fake: QSet() all: (QScreen(0x5631eb96c160, name="HDMI-0"), QScreen(0x5631eb96c250, name="DP-5"))
Checking screens: available: (QScreen(0x5631eb96c160, name="HDMI-0"), QScreen(0x5631eb96c250, name="DP-5")) redundant: QHash() fake: QSet() all: (QScreen(0x5631eb96c160, name="HDMI-0"), QScreen(0x5631eb96c250, name="DP-5"))
kf.plasma.quick: Applet preload policy set to 1
kf.coreaddons: Expected JSON property "X-Plasma-NotificationArea" to be a single string. but it is a bool
file:///usr/lib/qt/qml/org/kde/kirigami.2/templates/InlineMessage.qml:265:13: QML SelectableLabel: Binding loop detected for property "implicitWidth"
file:///usr/lib/qt/qml/org/kde/kirigami.2/templates/InlineMessage.qml:265:13: QML SelectableLabel: Binding loop detected for property "implicitWidth"
QObject::connect: No such slot DesktopProtocol::_k_slotRedirection(KIO::Job *, QUrl)
org.kde.plasma.containmentlayoutmanager: Error: cannot change the containment to AppletsLayout
Both point size and pixel size set. Using pixel size.
file:///usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/Tooltip.qml:78:9: QML GridLayout (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth"
org.kde.plasma.containmentlayoutmanager: Error: cannot change the containment to AppletsLayout
qt.gui.icc: fromIccProfile: failed minimal tag size sanity
qml: PlasmaExtras.ScrollArea is deprecated. Use PlasmaComponents3.ScrollView instead.
Module '.home.Azervivi..local.share.plasma.plasmoids.org.kde.contents.ui' does not contain a module identifier directive - it cannot be protected from external registrations.
file:///usr/share/plasma/plasmoids/org.kde.milou/contents/ui/main.qml:47:17: Unable to assign double to QQuickAnchorLine
org.kde.plasma.kicker: DragHelper is deprecated and will be removed in Plasma 6. Use Qt Quick Drag instead.
org.kde.plasma.kicker: Entry is not valid "kontact.desktop" QSharedPointer(0x5631edb39e40)
org.kde.plasma.kicker: Entry is not valid "ktp-contactlist.desktop" QSharedPointer(0x5631edb39310)
org.kde.plasma.kicker: Entry is not valid "org.kde.kate.desktop" QSharedPointer(0x5631edb3a180)
org.kde.plasma.kicker: Entry is not valid "org.kde.discover.desktop" QSharedPointer(0x5631edb38d80)
org.kde.plasma.kicker: Entry is not valid "kontact.desktop" QSharedPointer(0x5631edb39580)
org.kde.plasma.kicker: Entry is not valid "ktp-contactlist.desktop" QSharedPointer(0x5631edaf9fc0)
org.kde.plasma.kicker: Entry is not valid "org.kde.kate.desktop" QSharedPointer(0x5631edb3a8f0)
org.kde.plasma.kicker: Entry is not valid "org.kde.discover.desktop" QSharedPointer(0x5631edb38ef0)
file:///home/Azervivi/.local/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/Kickoff.qml:87: TypeError: Cannot read property 'height' of null
file:///home/Azervivi/.local/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/Kickoff.qml:63: TypeError: Cannot read property 'height' of null
QObject::connect: No such slot DesktopProtocol::_k_slotRedirection(KIO::Job *, QUrl)
file:///usr/share/plasma/plasmoids/org.kde.kscreen/contents/ui/main.qml:30:5: Unable to assign [undefined] to bool
Cyclic dependency detected between "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml" and "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/ThumbnailStrip.qml"
Cyclic dependency detected between "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml" and "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/NotificationHeader.qml"
file:///usr/share/plasma/plasmoids/org.kde.plasma.networkmanagement/contents/ui/main.qml:95: TypeError: Cannot read property 'airplaneModeAvailable' of null
kf.coreaddons: Expected JSON property "X-Plasma-NotificationArea" to be a single string. but it is a bool
file:///usr/share/plasma/plasmoids/org.kde.plasma.mediacontroller/contents/ui/CompactRepresentation.qml:136:5: QML Loader: Binding loop detected for property "width"
file:///usr/share/plasma/plasmoids/org.kde.plasma.networkmanagement/contents/ui/main.qml:95: TypeError: Cannot read property 'airplaneModeAvailable' of null
file:///usr/share/plasma/plasmoids/org.kde.kscreen/contents/ui/main.qml:30:5: Unable to assign [undefined] to bool
file:///usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/main.qml:18:1: QML MouseArea (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth"
org.kde.plasma.containmentlayoutmanager: Error: cannot change the containment to AppletsLayout
file:///usr/share/plasma/plasmoids/org.kde.milou/contents/ui/main.qml:47:17: Unable to assign double to QQuickAnchorLine
file:///home/Azervivi/.local/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/LeaveButtons.qml:64:5: QML ToolButton: Binding loop detected for property "display"
Both point size and pixel size set. Using pixel size.
file:///usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/Tooltip.qml:78:9: QML GridLayout (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth"
Both point size and pixel size set. Using pixel size.
org.kde.plasma.containmentlayoutmanager: Error: cannot change the containment to AppletsLayout
QObject::connect: No such slot DesktopProtocol::_k_slotRedirection(KIO::Job *, QUrl)
org.kde.plasma.pulseaudio: No object for name "bluez_output.AC_80_0A_6D_5B_81.1.monitor"
file:///usr/lib/qt/qml/org/kde/plasma/extras/PlaceholderMessage.qml:238:5: QML Heading: Binding loop detected for property "verticalAlignment"
file:///usr/lib/qt/qml/org/kde/plasma/extras/PlaceholderMessage.qml:238:5: QML Heading: Binding loop detected for property "verticalAlignment"
file:///usr/lib/qt/qml/org/kde/plasma/extras/PlaceholderMessage.qml:238:5: QML Heading: Binding loop detected for property "verticalAlignment"
`
To compare, here is the log without the Plasmaoid (the taskbar does show up)

`Checking screens: available: (QScreen(0x5600f262bb10, name="HDMI-0"), QScreen(0x5600f262bc00, name="DP-5")) redundant: QHash() fake: QSet() all: (QScreen(0x5600f262bb10, name="HDMI-0"), QScreen(0x5600f262bc00, name="DP-5"))
Checking screens: available: (QScreen(0x5600f262bb10, name="HDMI-0"), QScreen(0x5600f262bc00, name="DP-5")) redundant: QHash() fake: QSet() all: (QScreen(0x5600f262bb10, name="HDMI-0"), QScreen(0x5600f262bc00, name="DP-5"))
kf.plasma.quick: Applet preload policy set to 1
kf.coreaddons: Expected JSON property "X-Plasma-NotificationArea" to be a single string. but it is a bool
file:///usr/lib/qt/qml/org/kde/kirigami.2/templates/InlineMessage.qml:265:13: QML SelectableLabel: Binding loop detected for property "implicitWidth"
file:///usr/lib/qt/qml/org/kde/kirigami.2/templates/InlineMessage.qml:265:13: QML SelectableLabel: Binding loop detected for property "implicitWidth"
QObject::connect: No such slot DesktopProtocol::_k_slotRedirection(KIO::Job *, QUrl)
org.kde.plasma.containmentlayoutmanager: Error: cannot change the containment to AppletsLayout
Both point size and pixel size set. Using pixel size.
file:///usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/Tooltip.qml:78:9: QML GridLayout (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth"
org.kde.plasma.containmentlayoutmanager: Error: cannot change the containment to AppletsLayout
qt.gui.icc: fromIccProfile: failed minimal tag size sanity
qml: PlasmaExtras.ScrollArea is deprecated. Use PlasmaComponents3.ScrollView instead.
Module '.home.Azervivi..local.share.plasma.plasmoids.org.kde.contents.ui' does not contain a module identifier directive - it cannot be protected from external registrations.
file:///usr/share/plasma/plasmoids/org.kde.milou/contents/ui/main.qml:47:17: Unable to assign double to QQuickAnchorLine
org.kde.plasma.kicker: DragHelper is deprecated and will be removed in Plasma 6. Use Qt Quick Drag instead.
org.kde.plasma.kicker: Entry is not valid "kontact.desktop" QSharedPointer(0x5600f47103c0)
org.kde.plasma.kicker: Entry is not valid "ktp-contactlist.desktop" QSharedPointer(0x5600f470f890)
org.kde.plasma.kicker: Entry is not valid "org.kde.kate.desktop" QSharedPointer(0x5600f4710700)
org.kde.plasma.kicker: Entry is not valid "org.kde.discover.desktop" QSharedPointer(0x5600f470f300)
org.kde.plasma.kicker: Entry is not valid "kontact.desktop" QSharedPointer(0x5600f470fb00)
org.kde.plasma.kicker: Entry is not valid "ktp-contactlist.desktop" QSharedPointer(0x5600f46d0440)
org.kde.plasma.kicker: Entry is not valid "org.kde.kate.desktop" QSharedPointer(0x5600f4710e70)
org.kde.plasma.kicker: Entry is not valid "org.kde.discover.desktop" QSharedPointer(0x5600f470f470)
file:///home/Azervivi/.local/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/Kickoff.qml:87: TypeError: Cannot read property 'height' of null
file:///home/Azervivi/.local/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/Kickoff.qml:63: TypeError: Cannot read property 'height' of null
QObject::connect: No such slot DesktopProtocol::_k_slotRedirection(KIO::Job *, QUrl)
file:///usr/share/plasma/plasmoids/org.kde.kscreen/contents/ui/main.qml:30:5: Unable to assign [undefined] to bool
Cyclic dependency detected between "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml" and "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/ThumbnailStrip.qml"
Cyclic dependency detected between "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml" and "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/NotificationHeader.qml"
file:///usr/share/plasma/plasmoids/org.kde.plasma.networkmanagement/contents/ui/main.qml:95: TypeError: Cannot read property 'airplaneModeAvailable' of null
kf.coreaddons: Expected JSON property "X-Plasma-NotificationArea" to be a single string. but it is a bool
file:///usr/share/plasma/plasmoids/org.kde.plasma.mediacontroller/contents/ui/CompactRepresentation.qml:136:5: QML Loader: Binding loop detected for property "width"
file:///usr/share/plasma/plasmoids/org.kde.plasma.networkmanagement/contents/ui/main.qml:95: TypeError: Cannot read property 'airplaneModeAvailable' of null
org.kde.plasma.containmentlayoutmanager: Error: cannot change the containment to AppletsLayout
file:///usr/share/plasma/plasmoids/org.kde.kscreen/contents/ui/main.qml:30:5: Unable to assign [undefined] to bool
file:///usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/main.qml:18:1: QML MouseArea (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth"
file:///usr/share/plasma/plasmoids/org.kde.milou/contents/ui/main.qml:47:17: Unable to assign double to QQuickAnchorLine
file:///home/Azervivi/.local/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/LeaveButtons.qml:64:5: QML ToolButton: Binding loop detected for property "display"
Both point size and pixel size set. Using pixel size.
file:///usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/Tooltip.qml:78:9: QML GridLayout (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth"
Both point size and pixel size set. Using pixel size.
org.kde.plasma.containmentlayoutmanager: Error: cannot change the containment to AppletsLayout
QObject::connect: No such slot DesktopProtocol::_k_slotRedirection(KIO::Job *, QUrl)
org.kde.plasma.pulseaudio: No object for name "bluez_output.AC_80_0A_6D_5B_81.1.monitor"
`

Also when, adding the plasmoid, it is not visible. What is strange is that I did not encountered issue until yesterday, and then it stopped working. I suspect a package update did cause the issue.

Here are the package I updated just before encountering the issue :

`[2024-01-04T19:38:52+0100] [ALPM] upgraded c-ares (1.24.0-1 -> 1.25.0-1)
[2024-01-04T19:38:52+0100] [ALPM] installed electron28 (28.1.1-1)
[2024-01-04T19:38:52+0100] [ALPM] upgraded electron (1:25-1 -> 1:28-1)
[2024-01-04T19:38:52+0100] [ALPM] upgraded electron25 (25.9.6-1 -> 25.9.8-1)
[2024-01-04T19:38:52+0100] [ALPM] upgraded leptonica (1.84.0-1 -> 1.84.1-1)
[2024-01-04T19:38:53+0100] [ALPM] upgraded linux (6.6.8.arch1-1 -> 6.6.9.arch1-1)
[2024-01-04T19:38:54+0100] [ALPM] upgraded linux-headers (6.6.8.arch1-1 -> 6.6.9.arch1-1)
[2024-01-04T19:38:54+0100] [ALPM] upgraded nvidia (545.29.06-7 -> 545.29.06-8)
[2024-01-04T19:38:54+0100] [ALPM] upgraded python-pydantic-core (1:2.14.5-1 -> 1:2.14.6-1)
[2024-01-04T19:38:54+0100] [ALPM] upgraded python-pydantic (2.5.2-1 -> 2.5.3-1)
[2024-01-04T19:38:54+0100] [ALPM] upgraded python-jaraco.text (3.11.1-3 -> 3.12.0-1)
[2024-01-04T19:38:54+0100] [ALPM] upgraded rust (1:1.74.1-1 -> 1:1.75.0-1)
[2024-01-04T19:38:54+0100] [ALPM] upgraded starship (1.17.0-1 -> 1.17.1-1)`

**Comment by davidhi7** [comment]
I don't see any mentions of the widget in the log. Even if the widget was broken, Plasma should handle the errors instead of failing to launch. You might want to file a bug report for Plasmashell instead.
