### ISSUE TITLE
Bus /dev/i2c-16 not found Bus /dev/i2c-17 not found

### ISSUE THREAD

**Issue by ishaanbhimwal** [davidhi7/ddcci-plasmoid#65]
```
Bus /dev/i2c-16 not found
Bus /dev/i2c-17 not found
```

What should be done in this case?

**Comment by davidhi7** [comment]
Please provide some information on what actually happens and how to reproduce this.

**Comment by ishaanbhimwal** [comment]
Wow. Okay, it's working now. It wasn't working after rebooting, but removing and adding the widget again helped, apparently. Thanks for your reply and this wonderful extension!
