### ISSUE TITLE
USB c hub issue

### ISSUE THREAD

**Issue by ishaanbhimwal** [davidhi7/ddcci-plasmoid#67]
Hi! Thanks for your efforts, firstly. ddcutil detect is not able to find my monitor connected via a USB c hub? What can I do in this case?

**Comment by davidhi7** [comment]
ddcutil should work just fine with USB-C/Thunderbolt hubs and does in my setup. Try to plug the monitors directly into your device. Also make sure ddcutil is correctly setup (first section of the install guide) and make sure DDC/CI is enabled on the monitors (using the on-screen menu).

**Comment by ishaanbhimwal** [comment]
The extension only works when connect the monitor directly with HDMI and doesn't work when connected via the USB-C/Thunderbolt hub. I guess it's due to the hub not supporting certain "circuits". Anyway, thank you.
