### ISSUE TITLE
widget says backend is missing when it is not

### ISSUE THREAD

**Issue by rew1nter** [davidhi7/ddcci-plasmoid#76]
Clearly it's there. I installed with pipx. Why's it not working?
![image](https://github.com/davidhi7/ddcci-plasmoid/assets/64508791/34461e89-a1d3-41c8-8972-f52468ce1245)

**Comment by davidhi7** [comment]
See the 'important' note in [https://github.com/davidhi7/ddcci-plasmoid?tab=readme-ov-file#3-install-the-widget-itself](step 4 of the documentation)

**Comment by davidhi7** [comment]
No, you need to set the 'Backend executable command' in the widget settings (right click the widget > Settings or something like that) to `~/.local/bin/ddcci_plasmoid_backend`.

**Comment by rew1nter** [comment]
Did it. It's working now. thanks!
